version: 2
jobs:
  build-test:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Figure out which Docker services we should run CI for
          command: |
            ./should_run_ci.sh "$CIRCLE_BRANCH" "$CIRCLE_TAG"
            ./should_run_slow_tests.sh
      - run:
          name: Drop the override used for dev, and use Docker tags specific to this build
          command: |
            rm docker-compose.override.yml
            sed -i -e 's/image: \([^:]*\)$/image: \1:build-'$CIRCLE_BUILD_NUM'/' docker-compose.yml
      - run:
          name: Build Docker images
          command: |
            test -e skip-frontend || GIT_SHA1=$CIRCLE_SHA1 docker-compose build --pull frontend-db frontend-flask
      - run:
          name: Test and lint frontend server
          command: |
            test -e skip-frontend || {
              docker-compose build --pull frontend-flask-test
              # The image for the frontend-flask-test built above is named
              # bayesimpact/bob-emploi-frontend-server-test:build-$CIRCLE_BUILD_NUM
              docker create --name frontend-coverage-$CIRCLE_BUILD_NUM bayesimpact/bob-emploi-frontend-server-test:build-$CIRCLE_BUILD_NUM
              docker cp frontend-coverage-$CIRCLE_BUILD_NUM:/work/cover /tmp/frontend-coverage
              docker rm frontend-coverage-$CIRCLE_BUILD_NUM
            }
      - run:
          name: Test and lint frontend client
          command: |
            test -e skip-frontend || docker-compose build --pull frontend-dev
      - run:
          name: Test and lint data-analysis
          command: |
              test -e skip-data-analysis || {
                docker-compose build --pull data-analysis-prepare
                # The image for the data-analysis-prepare built above is named
                # docker.bayesimpact.org/bob-emploi/data-analysis-prepare:build-$CIRCLE_BUILD_NUM
                docker create --name data-analysis-prepare-$CIRCLE_BUILD_NUM docker.bayesimpact.org/bob-emploi/data-analysis-prepare:build-$CIRCLE_BUILD_NUM
                docker cp data-analysis-prepare-$CIRCLE_BUILD_NUM:/work/cover /tmp/data-analysis-coverage
                docker rm data-analysis-prepare-$CIRCLE_BUILD_NUM
              }
      - run:
          name: Make sure the export can be submitted
          command: |
            [[ "$(git log -1 --pretty=%B)" != *"DO NOT SUBMIT"* ]]
      - store_artifacts:
          path: /tmp/frontend-coverage
      - store_artifacts:
          path: /tmp/data-analysis-coverage

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/

experimental:
  notify:
    branches:
      only:
        - master
